apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api
  labels:
    app: mlops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
        - name: mlops-api
          image: mlops-api:jenkins-0   # Jenkins will update this tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
