apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
  labels:
    app: mlops-api
spec:
  type: NodePort
  selector:
    app: mlops-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
